namespace js JSAgentInterface
namespace py PYAgentInterface

struct ButtonStates
{
  1: bool WDown = false;
  2: bool ADown = false;
  3: bool SDown = false;
  4: bool DDown = false;
}

struct Point
{
  1: double x;
  2: double y;
  3: double z;
}

struct Pose
{
  1: Point pos;
  2: Point ori;
}

service AgentInterface
{
  void SetButtons(1:ButtonStates buttons),
  void Fire(),
  string GetSceneData(),
  Point GetPose()
}
