namespace js JSDataInterface
namespace py PYDataInterface

service DataInterface
{
  string GetGameData(1:string jsonData),
  void ExecuteTest(1:i32 testNumber),
  void ExecuteTests(),
  void RestartServer(),
  string GetTestCases(),
  string GetTestResults()
}
